const contohbiodatamahasiswa = {
  state: {
    contohbiodatamahasiswa: {
      header: [
        'nama_mahasiswa',
        'jenis_kelamin',
        'jalan',
        'rt',
        'rw',
        'kelurahan',
        'kode_pos',
        'nisn',
        'nik',
        'tempat_lahir',
        'tanggal_lahir',
        'nama_ayah',
        'tanggal_lahir_ayah',
        'id_pendidikan_ayah',
        'id_pekerjaan_ayah',
        'id_penghasilan_ayah',
        'id_kebutuhan_khusus_ayah',
        'nama_ibu_kandung',
        'tanggal_lahir_ibu',
        'id_pendidikan_ibu',
        'id_pekerjaan_ibu',
        'id_penghasilan_ibu',
        'id_kebutuhan_khusus_ibu',
        'nama_wali',
        'tanggal_lahir_wali',
        'id_pendidikan_wali',
        'id_pekerjaan_wali',
        'id_penghasilan_wali',
        'id_kebutuhan_khusus_mahasiswa',
        'telepon',
        'handphone',
        'email',
        'penerima_kps',
        'id_wilayah',
        'id_agama',
        'kewarganegaraan'
      ],
      data: [[
        'REYZA ALFIAN',
        'L',
        'Jl.Jati 2',
        0,
        0,
        'Samarinda',
        75000,
        9998,
        '64000000000000',
        'SAMARINDA',
        '1996-11-30',
        'SATRIO',
        '1970-11-30',
        0,
        0,
        1,
        0,
        'MURNI',
        '1972-10-30',
        0,
        0,
        1,
        0,
        '-',
        '1978-11-30',
        0,
        0,
        1,
        0,
        22227214054,
        22227214054,
        'a@gmail.com',
        0,
        160217,
        1,
        'ID'
      ]]
    }
  }
}

export default contohbiodatamahasiswa
